#!/usr/bin/env bash
# pre-compact-checkpoint.sh
# Auto-fires BEFORE /compact (and before auto-compact, if Claude Code triggers PreCompact for both).
# Captures observable state to docs/handoff/<timestamp>.md so post-compact has a recovery point.
#
# What it captures (no user interaction — must be silent):
#   1. Git activity since last checkpoint marker
#   2. Files changed (diff --stat)
#   3. Current TASK.md In Progress section
#   4. Recent F-NNN entries from local FAILS.md
#   5. Pointer to latest entries in Outline KB (if MCP set up)
#
# Does NOT block — exit 0 even if partial. Compact must proceed.

set +e  # Tolerate failures — checkpoint is best-effort, not blocking

GIT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0
HANDOFF_DIR="$GIT_ROOT/docs/handoff"
TS=$(date '+%Y-%m-%d-%H%M')
OUT="$HANDOFF_DIR/$TS.md"
POINTER="$GIT_ROOT/docs/handoff.md"
MARKER="$HANDOFF_DIR/.last-checkpoint"

mkdir -p "$HANDOFF_DIR"

# Determine "since when" — last checkpoint marker, or 24h ago, or session start
if [ -f "$MARKER" ]; then
  SINCE_TS=$(cat "$MARKER")
  SINCE_GIT="--since=$SINCE_TS"
else
  SINCE_GIT="--since=24.hours.ago"
fi

# Build the handoff document
{
  echo "# Pre-compact checkpoint — $TS"
  echo ""
  echo "_Auto-generated by PreCompact hook. Captures observable state. Edit to add human knowledge._"
  echo ""

  echo "## Git activity"
  COMMITS=$(git -C "$GIT_ROOT" log $SINCE_GIT --pretty="- %h %s" 2>/dev/null)
  if [ -n "$COMMITS" ]; then
    echo "$COMMITS"
  else
    echo "_No commits since last checkpoint._"
  fi
  echo ""

  echo "## Files changed"
  git -C "$GIT_ROOT" log $SINCE_GIT --name-only --pretty="" 2>/dev/null | \
    grep -v '^$' | sort -u | sed 's/^/- /' || echo "_None._"
  echo ""

  echo "## Working tree status (uncommitted)"
  STATUS=$(git -C "$GIT_ROOT" status --short 2>/dev/null)
  if [ -n "$STATUS" ]; then
    echo '```'
    echo "$STATUS"
    echo '```'
  else
    echo "_Clean._"
  fi
  echo ""

  echo "## Current In Progress (from docs/TASK.md)"
  if [ -f "$GIT_ROOT/docs/TASK.md" ]; then
    awk '/## In Progress/,/^## /' "$GIT_ROOT/docs/TASK.md" 2>/dev/null | head -30
  else
    echo "_docs/TASK.md not found._"
  fi
  echo ""

  echo "## Recent fails (last 5 entries from docs/FAILS.md)"
  if [ -f "$GIT_ROOT/docs/FAILS.md" ]; then
    grep -B 0 -A 10 "^## F-" "$GIT_ROOT/docs/FAILS.md" 2>/dev/null | tail -50
  else
    echo "_docs/FAILS.md not found._"
  fi
  echo ""

  echo "## Last spec opened"
  LATEST_SPEC=$(ls -t "$GIT_ROOT/docs/specs/"T-*.md 2>/dev/null | head -1)
  if [ -n "$LATEST_SPEC" ]; then
    echo "- $(basename "$LATEST_SPEC") ($(stat -f '%Sm' -t '%Y-%m-%d %H:%M' "$LATEST_SPEC"))"
    echo ""
    echo "_First 30 lines:_"
    echo '```'
    head -30 "$LATEST_SPEC"
    echo '```'
  else
    echo "_No specs in docs/specs/._"
  fi
  echo ""

  echo "## What's likely lost in this compact (heuristic)"
  echo "- Tool-call details from this session (file reads, grep results, edit-by-edit decisions)"
  echo "- Implicit decisions made via dialog (not in commit messages)"
  echo "- Approaches tried and abandoned"
  echo ""
  echo "**To preserve manually before /compact**: edit this file and add a section \`## Human knowledge\` with anything that's NOT in commits, files, or TASK.md."
  echo ""

  echo "---"
  echo "Next session: read THIS file (\`docs/handoff.md\` points to it). Then delete this file after picking up context."
} > "$OUT"

# Update single-file pointer for next session start
{
  echo "# Latest handoff"
  echo ""
  echo "Latest checkpoint: [$TS]($(realpath --relative-to="$GIT_ROOT" "$OUT" 2>/dev/null || echo "handoff/$TS.md"))"
  echo ""
  echo "Older entries in \`docs/handoff/\` directory."
  echo ""
  echo "_Auto-generated by .claude/hooks/pre-compact-checkpoint.sh on $(date '+%Y-%m-%d %H:%M:%S')_"
} > "$POINTER"

# Update marker for next checkpoint diff window
date '+%Y-%m-%d %H:%M:%S' > "$MARKER"

# Notify via stderr (will be visible in Claude Code log)
echo "[PRE-COMPACT CHECKPOINT] Saved to $OUT" >&2
echo "[PRE-COMPACT CHECKPOINT] Edit it now to add human knowledge before compact runs." >&2

# Archive old checkpoints (>30 days) to keep the dir manageable
find "$HANDOFF_DIR" -name "*.md" -mtime +30 -exec mv {} "$HANDOFF_DIR/archive/" \; 2>/dev/null || true

exit 0
